'use strict';
const $=id=>document.getElementById(id),P=Progress,STORE='hanyang-study-shared-v3';
const labels={recall:'학습 준비 / 복습',read:'교재 읽기',exercise:'문제 풀기',oral:'면접 준비',note:'메모 작성'};
const dayAdd=(day,n)=>{const d=new Date(day+'T12:00:00');d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const offset=(day,start)=>Math.round((Date.parse(day+'T12:00:00Z')-Date.parse(start+'T12:00:00Z'))/86400000);
let doc=P.empty(),schedule,course,selected,desktop=false,token='',syncing=false,timer,localTimer,connected=false,lastStamp=0,noteTimer,pendingNote=null;
const device=crypto.randomUUID();
function stamp(){lastStamp=Math.max(Date.now(),lastStamp+1,...Object.values(doc.fields).map(v=>Number(v.stamp.slice(0,13))+1),...Object.values(doc.notes).flatMap(n=>Object.keys(n).map(s=>Number(s.slice(0,13))+1)));return `${String(lastStamp).padStart(13,'0')}-${device}`}
const value=(k,f)=>P.value(doc,k,f),start=()=>value('start_date','2026-09-16');
function plan(day){const i=offset(day,start());let e=schedule.weeks[Math.floor(i/7)]?.days[i%7];if(i>=49)e={title:'면접 직전 · 오답과 구술 복습',scope:'설명이 막혔던 질문과 핵심 개념 복습',exercise:'오답 예제의 입력을 바꾸어 다시 풀기',oral:'30초 답변 5개와 연구 설명 1회',sections:[['linear','trees','hashing'],['sorting','graphs'],['process','memory','synchronization'],['network'],['oop','database'],['discrete','extensions'],['research-bridge','mock']][(i-49)%7]};return e?{...e,index:i}:null}
const done=(day,id)=>value(`done:${day}:${id}`,false);
function complete(day){return !!plan(day)&&Object.keys(labels).every(id=>done(day,id))}
function current(){let day=start();for(let n=0;n<10000&&complete(day)&&value('unlock:'+dayAdd(day,1),false);n++)day=dayAdd(day,1);return day}
function locked(day){return !plan(day)||day>current()}
function persist(){localStorage.setItem(STORE,JSON.stringify(doc));if(desktop){clearTimeout(localTimer);localTimer=setTimeout(saveDesktop,200)}if(connected){clearTimeout(timer);timer=setTimeout(sync,1600)}}
function field(key,val){doc.fields[key]={value:val,stamp:stamp()};persist()}
async function saveDesktop(){try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(doc)});if(!r.ok)throw Error(await r.text());doc=P.merge(doc,await r.json());localStorage.setItem(STORE,JSON.stringify(doc))}catch(e){$('status').textContent='PC 기록 저장 실패: '+e.message}}
function text(tag,content,cls){const el=document.createElement(tag);el.textContent=content;if(cls)el.className=cls;return el}
function navigate(day,part='read'){selected=day;render();location.hash=part;requestAnimationFrame(()=>document.getElementById(part)?.scrollIntoView())}
function flushNote(){if(pendingNote){clearTimeout(noteTimer);const {day,value}=pendingNote;pendingNote=null;doc.notes[day]??={};doc.notes[day][stamp()]=value;persist()}}
function render(){flushNote();const p=plan(selected),isLocked=locked(selected);$('title').textContent=p?.title||'학습 시작 전';$('stageLabel').textContent=`${offset(selected,start())+1}단계 · 계획일 ${selected}`;$('scope').textContent=p?.scope||'';const count=Object.keys(labels).filter(id=>done(selected,id)).length;$('progress').value=count;$('count').textContent=`${count}/5 완료`;$('tasks').replaceChildren();
for(const [id,label] of Object.entries(labels)){const row=text('div','','task'),check=document.createElement('input');check.type='checkbox';check.checked=done(selected,id);check.disabled=isLocked;check.setAttribute('aria-label',label+' 완료');check.onchange=()=>{field(`done:${selected}:${id}`,check.checked);render()};const body=document.createElement('div'),button=text('button',label,'task-button');button.disabled=isLocked;button.onclick=()=>{location.hash=id;document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};body.append(button,text('small',id==='read'?p?.scope||'':id==='exercise'?p?.exercise||'':id==='oral'?p?.oral||'':id==='note'?'막힌 질문과 다시 볼 내용 기록':'전 단계 핵심 3개 말하기'));row.append(check,body);$('tasks').append(row)}
$('unlock').disabled=isLocked||!complete(selected);$('unlock').textContent=value('unlock:'+dayAdd(selected,1),false)?'다음 단계로 →':'다음 단계 해금 →';$('gate').textContent=isLocked?'이전 단계의 체크를 모두 완료한 뒤 해금 버튼을 눌러 주세요.':complete(selected)?'날짜를 기다리지 않고 다음 단계를 해금할 수 있어요.':'체크 목록을 모두 완료하면 다음 단계 해금 버튼이 활성화돼요.';$('start').value=start();$('exam').value=value('interview_date','');renderReader(p,isLocked)}

function remapIds(node,prefix){const ids=new Map();for(const el of node.querySelectorAll('[id]')){ids.set(el.id,prefix+'-'+el.id);el.id=prefix+'-'+el.id}for(const el of node.querySelectorAll('*'))for(const attr of [...el.attributes]){let v=attr.value;for(const [oldId,newId] of ids)v=v.replaceAll('url(#'+oldId+')','url(#'+newId+')');if(v!==attr.value)el.setAttribute(attr.name,v)}}
function part(id,title,number){const s=text('section','','study-part');s.id=id;s.append(text('span',number,'part-number'),text('h2',title));return s}
function renderReader(p,isLocked){const root=$('reader');root.replaceChildren();if(isLocked){root.append(text('section','잠긴 단계입니다. 이전 학습을 마치고 해금해 주세요.','card locked-page'));return}const nav=text('nav','','reader-nav');for(const [id,label] of Object.entries(labels)){const a=text('a',label);a.href='#'+id;nav.append(a)}const al=text('a','원본 부록');al.href='#appendix';nav.append(al);root.append(nav);
const recall=part('recall',p.index===0?'학습 준비':'이전 학습 복습','START');recall.append(text('p',p.index===0?'지금 알고 있는 내용과 이번 학습 목표를 세 문장으로 정리하세요.':'책을 덮고 이전 단계의 핵심 세 가지를 말해 보세요.'));root.append(recall);
const read=part('read','오늘 공부할 이론','01 · THEORY'),exercise=part('exercise','순서대로 풀어 볼 문제','02 · PRACTICE'),oral=part('oral','면접 준비 질문','03 · INTERVIEW');read.append(text('p',p.scope,'prompt'));exercise.append(text('p','1. '+p.exercise,'prompt'));oral.append(text('p','먼저 답해 보기: '+p.oral,'prompt'));let q=2,o=1;
for(const id of p.sections){const original=course.getElementById(id);if(!original){read.append(text('p','교재 절을 찾지 못했습니다: '+id));continue}const theory=original.cloneNode(true);theory.removeAttribute('id');const heading=theory.querySelector('h2')?.textContent||id;
for(const el of [...theory.querySelectorAll('details.quiz, details.follow, .answer')]){const filter=LESSON_QUESTIONS[p.index+1];if(filter&&!new RegExp(filter,'i').test(el.textContent)){el.remove();continue}const copy=el.cloneNode(true);remapIds(copy,id+'-q'+q+'-o'+o);if(el.matches('details.quiz')){const sum=copy.querySelector('summary');if(sum)sum.textContent=`${q++}. ${sum.textContent}`;exercise.append(text('h3',heading),copy)}else if(el.matches('details.follow')){const sum=copy.querySelector('summary');if(sum)sum.textContent=`${o++}. ${sum.textContent}`;oral.append(copy)}else{const detail=document.createElement('details');detail.append(text('summary',heading+' · 답변 예시'),copy);oral.append(detail)}el.remove()}
const headings=LESSON_SCOPE[p.index+1]?.[id];if(headings){let keep=true;for(const node of [...theory.children]){if(node.tagName==='H3')keep=headings.some(h=>node.textContent.startsWith(h));if(!keep)node.remove()}}remapIds(theory,id);if(id==='mock'){oral.append(theory);read.append(text('p','모의면접 방법: 정의·예시·조건을 점검하고, 아래 면접 준비 구획에서 세트별 질문에 답하세요.'))}else read.append(theory)}
exercise.append(text('p','풀이 순서: 답을 먼저 예측 → 이유를 적기 → 해설 펼치기 → 조건을 바꿔 다시 풀기.'));oral.append(text('p','정의 → 예시 → 조건과 한계 순서로, 답변 예시를 보기 전에 소리 내어 말해 보세요.'));root.append(read,exercise,oral);
const notes=part('note','막힌 질문과 다시 볼 내용','04 · NOTES'),area=document.createElement('textarea');area.rows=9;area.id='memo';area.setAttribute('aria-label','학습 메모');area.placeholder='잘 설명하지 못한 개념, 질문, 다음에 확인할 내용을 기록하세요.';area.value=P.note(doc,selected);const saved=text('p','이 기기에 자동 저장됩니다.','muted');saved.id='noteSave';area.oninput=()=>{pendingNote={day:selected,value:area.value};clearTimeout(noteTimer);noteTimer=setTimeout(()=>{flushNote();saved.textContent='이 기기에 저장됨 · 동기화 상태는 설정에서 확인'},600);saved.textContent='저장 중…'};notes.append(area,saved);const history=document.createElement('details');history.append(text('summary','이전 메모 / 다른 기기에서 작성한 내용'));for(const [key,val] of Object.entries(doc.notes[selected]||{}).sort().reverse().slice(0,20)){history.append(text('small',new Date(Number(key.slice(0,13))).toLocaleString()),text('p',val||'(빈 메모)'))}notes.append(history);root.append(notes);
const appendix=part('appendix','원본 · 대학원면접대비속성자료','APPENDIX');appendix.append(text('p','원본의 순서와 페이지를 그대로 보존했습니다. 학습 본문은 원본 주제를 중심으로 C 입문 설명과 예제를 보충한 것입니다. 별표는 원문 강조 표시이며 기출 확률을 뜻하지 않습니다.'));const a=text('a','원본 PDF 열기 / 다운로드');a.href='original.pdf';a.target='_blank';a.rel='noopener';appendix.append(a);const mapping=document.createElement('details');mapping.append(text('summary','원본과 교재의 범위 대조'));const audit=course.getElementById('source-audit');if(audit)mapping.append(audit.cloneNode(true));appendix.append(mapping);for(let n=1;n<=16;n++){const d=document.createElement('details');d.append(text('summary',`원본 ${n}쪽`));const img=document.createElement('img');img.src=`original-pages/page-${String(n).padStart(2,'0')}.png`;img.alt=`대학원면접대비속성자료 원본 ${n}쪽`;img.loading='lazy';img.className='appendix-page';d.append(img);appendix.append(d)}root.append(appendix)}
async function github(path,options={}){let url='https://api.github.com/repos/seung-ddak/Hanyang'+path;const headers={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...options.headers};if(desktop)url='/api/github'+path;else headers.Authorization='Bearer '+token;const r=await fetch(url,{...options,headers,cache:'no-store'});if(!r.ok){const e=Error(`GitHub ${r.status}: ${r.status===401?'인증 정보를 확인하세요':r.status===403?'권한 또는 요청 한도를 확인하세요':'동기화를 완료하지 못했습니다'}`);e.status=r.status;throw e}return r.status===204?null:r.json()}
const encode=obj=>btoa(Array.from(new TextEncoder().encode(JSON.stringify(obj,null,2)),b=>String.fromCharCode(b)).join(''));
const decode=str=>JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(str.replace(/\s/g,'')),c=>c.charCodeAt(0))));
async function sync(){flushNote();if(syncing)return;if(!desktop&&!token){$('syncStatus').textContent='GitHub 토큰을 입력해 연결하세요.';return}syncing=true;$('syncStatus').textContent='동기화 중…';try{const repo=await github('');if(!repo.private)throw Error('저장소가 공개 상태여서 기록 업로드를 중단했습니다.');for(let attempt=0;attempt<3;attempt++){let remote,sha;try{const f=await github('/contents/progress/state.json?ref=study-progress');remote=decode(f.content);sha=f.sha}catch(e){if(e.status!==404)throw e;remote=P.empty()}doc=P.merge(doc,remote);const snapshot=JSON.stringify(doc);try{if(JSON.stringify(doc)!==JSON.stringify(remote))await github('/contents/progress/state.json',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Sync study progress',branch:'study-progress',content:encode(doc),...(sha?{sha}:{})})});connected=true;localStorage.setItem(STORE,JSON.stringify(doc));if(desktop)await saveDesktop();$('syncStatus').textContent='동기화 완료 · '+new Date().toLocaleTimeString();if(document.activeElement?.id!=='memo')render();if(snapshot!==JSON.stringify(doc)){clearTimeout(timer);timer=setTimeout(sync,1000)}return}catch(e){if(e.status!==409&&e.status!==422)throw e;if(attempt===2)throw Error('동시 저장으로 재시도가 필요합니다.')}}}catch(e){$('syncStatus').textContent=e.message+' · 기록은 이 기기에 보존됨'}finally{syncing=false}}
function migrate(){const old=JSON.parse(localStorage.getItem('hanyang-study-pwa-v2')||'null');if(!old)return;const st=JSON.parse(localStorage.getItem('hanyang-study-pwa-settings-v2')||'{}');for(const [day,entry] of Object.entries(old.days||{})){for(const id of entry.done||[])doc.fields[`done:${day}:${id}`]={value:true,stamp:stamp()};if(entry.note)doc.notes[day]={[stamp()]:entry.note}}if(st.start_date)doc.fields.start_date={value:st.start_date,stamp:stamp()};localStorage.setItem(STORE,JSON.stringify(doc))}
async function init(){try{[schedule,course]=await Promise.all([fetch('study_schedule.json',{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('Study schedule failed to load (HTTP '+r.status+')');const data=await r.json();if(!Array.isArray(data.weeks)||!data.weeks.length)throw Error('Invalid study schedule format.');return data}),fetch('course.html',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Textbook failed to load (HTTP '+r.status+')');return r.text()}).then(s=>new DOMParser().parseFromString(s,'text/html'))]);const stored=localStorage.getItem(STORE);if(stored)doc=P.validate(JSON.parse(stored));else migrate();if(location.hostname==='127.0.0.1'||location.hostname==='localhost'){try{const r=await fetch('/api/state',{cache:'no-store'});if(r.ok){doc=P.merge(doc,await r.json());desktop=true;$('tokenLabel').hidden=true;$('disconnect').hidden=true;$('tokenHelp').textContent='PC의 GitHub 로그인으로 동기화합니다.'}}catch{}}selected=new URLSearchParams(location.search).get('day')||current();if(!/^\d{4}-\d{2}-\d{2}$/.test(selected))selected=current();render();requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView());if(desktop){connected=true;sync()}if('serviceWorker'in navigator&&!desktop)navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch(e){$('status').textContent='Loading failed: '+e.message;$('reader').textContent='Textbook failed to load: '+e.message}}
$('reader').addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;const id=a.getAttribute('href').slice(1);if(document.getElementById(id))return;e.preventDefault();for(let n=0;n<49;n++){const day=dayAdd(start(),n);if(plan(day)?.sections.includes(id)&&!locked(day)){navigate(day);return}}$('status').textContent='이 절은 아직 잠겨 있습니다. 이전 단계를 먼저 완료해 주세요.'});
$('prev').onclick=()=>navigate(dayAdd(selected,-1));$('next').onclick=()=>navigate(dayAdd(selected,1));$('current').onclick=()=>navigate(current());$('unlock').onclick=()=>{if(locked(selected)||!complete(selected))return;const next=dayAdd(selected,1);field('unlock:'+next,true);navigate(next)};
$('sync').onclick=()=>{token=$('token').value.trim();$('token').value='';connected=true;sync()};$('disconnect').onclick=()=>{connected=false;token='';$('token').value='';clearTimeout(timer);$('syncStatus').textContent='이 기기의 자동 동기화 연결을 해제했습니다.'};
$('start').onchange=()=>{if(!$('start').value)return;field('start_date',$('start').value);navigate(current())};$('exam').onchange=()=>field('interview_date',$('exam').value);
$('export').onclick=()=>{flushNote();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}));a.download='hanyang-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('import').onchange=async()=>{try{doc=P.merge(doc,P.validate(JSON.parse(await $('import').files[0].text())));persist();navigate(current())}catch(e){$('status').textContent='가져오기 실패: '+e.message}};
window.addEventListener('storage',e=>{if(e.key===STORE&&e.newValue){try{doc=P.merge(doc,P.validate(JSON.parse(e.newValue)));if(document.activeElement?.id!=='memo')render()}catch{}}});window.addEventListener('online',()=>{if(connected)sync()});window.addEventListener('focus',()=>{if(connected)sync()});setInterval(()=>{if(connected)sync()},60000);
window.addEventListener('pagehide',flushNote);
init();
